'use client';

import { useState, useEffect, useCallback } from 'react';
import { useRouter, useSearchParams } from 'next/navigation';
import { jsPDF } from 'jspdf';
import { generateCCPAReport } from './actions';

export default function CCPACheckerClient() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const isPaid = searchParams.get('paid') === 'true';

  const [step, setStep] = useState(1);
  const [answers, setAnswers] = useState({
    dataType: '',
    userScale: '',
    encrypted: ''
  });
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [showResults, setShowResults] = useState(false);
  const [activeTab, setActiveTab] = useState('draft');
  const [confidence, setConfidence] = useState(0);
  
  // Phase 2: Real AI Data
  const [realData, setRealData] = useState<{ letter: string; analysis: any[] } | null>(null);
  const [error, setError] = useState<string | null>(null);

  // Phase 1 Mock Results
  const mockRiskLevel = "High";
  const mockDamages = "$100 - $750 per consumer";
  
  const handleStep = (value: string) => {
    const newAnswers = { ...answers };
    if (step === 1) newAnswers.dataType = value;
    if (step === 2) newAnswers.userScale = value;
    if (step === 3) {
      newAnswers.encrypted = value;
      setIsAnalyzing(true);
    }
    
    setAnswers(newAnswers);
    
    if (step < 3) {
      setStep(step + 1);
    }
  };

  const fetchRealReport = useCallback(async () => {
    try {
      const response = await generateCCPAReport(answers);
      if (response.success) {
        setRealData(response.data);
      } else {
        setError(response.error || "Failed to generate report.");
      }
    } catch (e: any) {
      setError(e.message || "An unexpected error occurred.");
    }
  }, [answers]);

  useEffect(() => {
    if (isAnalyzing) {
      let timer = 0;
      const interval = setInterval(() => {
        timer += 5;
        setConfidence(timer);
        if (timer >= 98) {
          clearInterval(interval);
          setIsAnalyzing(false);
          setShowResults(true);
          
          if (isPaid) {
            fetchRealReport();
          }
        }
      }, 50);
      return () => clearInterval(interval);
    }
  }, [isAnalyzing, isPaid, fetchRealReport]);

  const handleUnlock = () => {
    router.push(`/tools/ccpa-checker?paid=true&unlock=success`);
  };

  const downloadPDF = () => {
    if (!realData) return;
    
    const doc = new jsPDF();
    
    // Header
    doc.setFont("helvetica", "bold");
    doc.setFontSize(16);
    doc.text("PANCO LEGAL ASSISTANT", 20, 20);
    
    // Horizontal Line
    doc.setLineWidth(0.5);
    doc.line(20, 25, 190, 25);
    
    // Title
    doc.setFontSize(18);
    doc.text("NOTICE OF DATA BREACH", 20, 40);
    
    // Sub-info
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.text(`Target Location: California, USA`, 20, 50);
    doc.text(`Date: ${new Date().toLocaleDateString()} ${new Date().toLocaleTimeString()}`, 20, 55);
    doc.text("CCPA Section 1798.82 Compliant Notice", 20, 60);
    
    // Main Content
    doc.setFontSize(11);
    const splitText = doc.splitTextToSize(realData.letter, 170);
    doc.text(splitText, 20, 75);
    
    // Footer
    const pageHeight = doc.internal.pageSize.height;
    doc.setFontSize(8);
    doc.setFont("helvetica", "italic");
    const footerText = "Generated by Panco AI. This report is for informational purposes only and does not constitute legal advice.";
    const splitFooter = doc.splitTextToSize(footerText, 170);
    doc.text(splitFooter, 20, pageHeight - 20);
    
    doc.save(`Panco_CCPA_Notice_${new Date().getTime()}.pdf`);
  };

  return (
    <section className="text-center space-y-6 pt-6">
      <div className="inline-flex items-center gap-2 rounded-full bg-primary-lavender/10 px-4 py-1.5 text-xs font-bold text-text-lavender uppercase tracking-widest">
        AI Legal Tool
      </div>
      <h1 className="text-4xl md:text-5xl font-extrabold text-text-primary tracking-tight">
        CCPA Compliance Checker <br />
        <span className="text-primary-lavender">& Data Breach Letter Generator</span>
      </h1>
      <p className="max-w-2xl mx-auto text-lg text-text-primary/60">
        Instant CCPA compliance check for California startups. Generate data breach notification letters in minutes. No hourly legal fees.
      </p>

      {!showResults && !isAnalyzing && (
        <div className="max-w-2xl mx-auto mt-12 p-8 bg-white rounded-3xl border border-border-lavender shadow-soft relative overflow-hidden text-left">
          <div className="absolute top-0 left-0 w-full h-1 bg-gray-100">
             <div 
              className="h-full bg-primary-lavender transition-all duration-500" 
              style={{ width: `${(step / 3) * 100}%` }}
             />
          </div>
          
          <div className="pt-4">
            <span className="text-xs font-bold text-primary-lavender uppercase mb-2 block">Step {step} of 3</span>
            <h2 className="text-2xl font-bold mb-8">
              {step === 1 && "What type of consumer data was involved?"}
              {step === 2 && "How many California residents are affected?"}
              {step === 3 && "Was the data encrypted at the time of the breach?"}
            </h2>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {step === 1 && ["Email", "SSN", "Biometric", "Financial"].map(opt => (
                <button key={opt} onClick={() => handleStep(opt)} className="py-4 px-6 bg-white border border-gray-200 rounded-2xl hover:border-primary-lavender hover:bg-primary-lavender/5 text-left font-bold transition-all hover:shadow-md active:scale-95">{opt}</button>
              ))}
              {step === 2 && ["<500", "500+"].map(opt => (
                <button key={opt} onClick={() => handleStep(opt)} className="py-4 px-6 bg-white border border-gray-200 rounded-2xl hover:border-primary-lavender hover:bg-primary-lavender/5 text-left font-bold transition-all hover:shadow-md active:scale-95">{opt === "<500" ? "Less than 500" : "500 or more"}</button>
              ))}
              {step === 3 && ["Yes", "No"].map(opt => (
                <button key={opt} onClick={() => handleStep(opt)} className="py-4 px-6 bg-white border border-gray-200 rounded-2xl hover:border-primary-lavender hover:bg-primary-lavender/5 text-left font-bold transition-all hover:shadow-md active:scale-95">{opt}</button>
              ))}
            </div>
          </div>
        </div>
      )}

      {isAnalyzing && (
        <div className="max-w-2xl mx-auto mt-12 p-12 bg-white rounded-3xl border border-border-lavender shadow-soft text-center space-y-6">
          <div className="w-20 h-20 border-4 border-primary-lavender/20 border-t-primary-lavender rounded-full animate-spin mx-auto" />
          <div className="space-y-2">
            <p className="text-xl font-bold text-text-primary">Analyzing CCPA 2026 Regulations...</p>
            <div className="w-full bg-gray-100 h-2 rounded-full max-w-xs mx-auto overflow-hidden">
              <div className="h-full bg-primary-lavender transition-all duration-300" style={{ width: `${confidence}%` }} />
            </div>
            <p className="text-sm text-text-primary/40 font-mono">AI Confidence Score: {confidence}%</p>
          </div>
        </div>
      )}

      {showResults && (
        <div className="max-w-4xl mx-auto mt-12 space-y-8 animate-in fade-in slide-in-from-bottom-4 duration-700 text-left">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div className="bg-red-50 p-6 rounded-2xl border border-red-100 text-left">
              <span className="text-xs font-bold text-red-600 uppercase">Risk Level</span>
              <p className="text-3xl font-black text-red-700 mt-1">{mockRiskLevel}</p>
              <p className="text-sm text-red-600/70 mt-2">Based on sensitive data type and disclosure scale.</p>
            </div>
            <div className="bg-amber-50 p-6 rounded-2xl border border-amber-100 text-left">
              <span className="text-xs font-bold text-amber-600 uppercase">Potential Damages</span>
              <p className="text-3xl font-black text-amber-700 mt-1">{mockDamages}</p>
              <p className="text-sm text-amber-600/70 mt-2">Per consumer under CCPA Section 1798.150.</p>
            </div>
          </div>

          <div className="bg-white rounded-3xl border border-border-lavender shadow-soft overflow-hidden text-left">
            <div className="flex border-b border-gray-100">
              <button 
                onClick={() => setActiveTab('draft')}
                className={`px-8 py-4 text-sm font-bold transition-all ${activeTab === 'draft' ? 'text-primary-lavender border-b-2 border-primary-lavender bg-primary-lavender/5' : 'text-text-primary/40 hover:text-text-primary'}`}
              >
                Notification Draft
              </button>
              <button 
                onClick={() => setActiveTab('analysis')}
                className={`px-8 py-4 text-sm font-bold transition-all ${activeTab === 'analysis' ? 'text-primary-lavender border-b-2 border-primary-lavender bg-primary-lavender/5' : 'text-text-primary/40 hover:text-text-primary'}`}
              >
                Risk Analysis
              </button>
            </div>

            <div className="p-8">
              {activeTab === 'draft' ? (
                <div className="relative group">
                  <div className={`bg-gray-50 rounded-xl p-6 font-mono text-sm text-gray-800 leading-relaxed transition-all ${!isPaid ? 'blur-sm select-none' : ''}`}>
                    {isPaid ? (
                      realData ? (
                        <div className="whitespace-pre-wrap">
                          {realData.letter}
                        </div>
                      ) : error ? (
                        <div className="text-red-500 font-bold p-10 text-center">
                          Error: {error}
                          <br />
                          <button onClick={fetchRealReport} className="text-sm underline mt-4">Retry Call</button>
                        </div>
                      ) : (
                        <div className="flex flex-col items-center justify-center py-20">
                          <div className="animate-spin h-8 w-8 border-b-2 border-primary-lavender mb-4" />
                          <p className="text-primary-lavender font-bold">DeepSeek AI is drafting your notification letter...</p>
                        </div>
                      )
                    ) : (
                      <>
                        <div className="flex justify-between mb-4 border-b pb-2 border-gray-200">
                          <span>Subject: NOTICE OF DATA BREACH</span>
                          <span>[MOCKED CONTENT]</span>
                        </div>
                        <p>Dear [Consumer Name],</p>
                        <br />
                        <p>We are writing to inform you of a security incident that may have involved your personal information...</p>
                        <br />
                        <p>Under the California Consumer Privacy Act (CCPA), you have the right to know what personal information was collected and for what purpose...</p>
                        <p>As part of our commitment to your privacy, we recommend taking the following steps: [LOCKED]</p>
                        <br />
                        <p>Sincerely,</p>
                        <p>[Company Compliance Representative]</p>
                      </>
                    )}
                  </div>
                  {!isPaid && (
                    <div className="absolute inset-0 flex flex-col items-center justify-center bg-white/20 backdrop-blur-[2px] rounded-xl">
                      <button 
                        onClick={handleUnlock}
                        className="px-8 py-4 bg-primary-lavender text-white font-bold rounded-xl shadow-lg hover:bg-primary-lavender-dark transition-all transform hover:scale-105"
                      >
                        Unlock Official CCPA Notification (3 Credits)
                      </button>
                      <p className="mt-4 text-sm font-semibold text-text-lavender">Instant PDF Generation Included</p>
                    </div>
                  )}
                    {isPaid && realData && (
                      <div className="absolute top-4 right-4 flex gap-2">
                        <button 
                          onClick={() => {
                            navigator.clipboard.writeText(realData.letter);
                            alert("Draft copied to clipboard!");
                          }}
                          className="p-2 bg-white border border-gray-100 rounded text-gray-400 hover:text-primary-lavender transition-colors"
                        >
                          Copy
                        </button>
                      </div>
                    )}
                </div>
              ) : (
                <div className="space-y-6">
                  <div className="grid grid-cols-1 gap-4">
                    {isPaid && realData ? (
                      realData.analysis.map((point: any, idx: number) => (
                        <div key={idx} className={`flex items-start gap-4 p-4 rounded-xl border ${point.severity === 'High' ? 'border-red-50 bg-red-50/30' : 'border-amber-50 bg-amber-50/30'}`}>
                          <span className="text-xl">{point.severity === 'High' ? '⚖️' : '⚠️'}</span>
                          <div>
                            <p className="font-bold text-gray-900">{point.title}</p>
                            <p className="text-sm text-gray-600 mt-1">{point.description}</p>
                          </div>
                        </div>
                      ))
                    ) : (
                      <>
                        <div className="flex items-start gap-4 p-4 rounded-xl border border-red-50 bg-red-50/30">
                          <span className="text-xl">⚖️</span>
                          <div>
                            <p className="font-bold text-gray-900">Section 1798.82 Violation Risdk</p>
                            <p className="text-sm text-gray-600 mt-1">Notification timing may exceed 'without unreasonable delay' criteria.</p>
                          </div>
                        </div>
                        <div className="flex items-start gap-4 p-4 rounded-xl border border-amber-50 bg-amber-50/30">
                          <span className="text-xl">⚠️</span>
                          <div>
                            <p className="font-bold text-gray-900">Statutory Damages Eligibility</p>
                            <p className="text-sm text-gray-600 mt-1">Sensitive data (SSN/Financial) triggers Section 1798.150(a)(1) private action rights.</p>
                          </div>
                        </div>
                      </>
                    )}
                  </div>
                  {!isPaid && (
                    <div className="text-center pt-4">
                      <button 
                        onClick={handleUnlock}
                        className="text-primary-lavender font-bold hover:underline"
                      >
                        Unlock Full Risk Report →
                      </button>
                    </div>
                  )}
                </div>
              )}
            </div>
          </div>

          <div className="flex items-center justify-between px-6 py-4 bg-bg-card rounded-2xl border border-border-lavender">
            <div className="flex items-center gap-3">
              <div className="w-12 h-12 bg-green-100 flex items-center justify-center rounded-full text-green-600 font-bold text-xs ring-4 ring-green-50">
                98%
              </div>
              <div>
                <p className="text-sm font-bold text-text-primary">AI Confidence Score</p>
                <p className="text-xs text-text-primary/40">Verified against 2026 CCPA Amendments</p>
              </div>
            </div>
            <div className="flex items-center gap-3">
              <button 
                onClick={isPaid && realData ? downloadPDF : handleUnlock}
                className={`text-xs font-bold text-white bg-primary-lavender px-4 py-2 rounded-lg hover:bg-primary-lavender-dark transition-colors ${isPaid && !realData ? 'opacity-50 cursor-not-allowed' : ''}`}
                id="btn-download-pdf"
              >
                {isPaid ? "Download Official PDF" : "Unlock PDF Generation"}
              </button>
            </div>
          </div>
        </div>
      )}
    </section>
  );
}
